---
- name: Restart filebeat
  become: true
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
  tags:
    - services

- name: Restart metricbeat
  become: true
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
  tags:
    - services

- name: Restart auditbeat
  become: true
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
  tags:
    - services

- name: Restart packetbeat
  become: true
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
  tags:
    - services
