- name: Gather facts from all hosts
  hosts: all
  gather_facts: true

- name: Apply redelk_server role to monitoring server(s)
  hosts: monitoring
  gather_facts: true
  tags:
    - monitoring
  roles:
    - redelk_server

- name: Apply redelk_client role to teamservers
  hosts: teamservers
  gather_facts: true
  tags:
    - teamservers
  roles:
    - redelk_client

- name: Apply redelk_client role to redirectors
  hosts: redirectors
  gather_facts: true
  tags:
    - redirectors
  roles:
    - redelk_client
