---
- name: Installing docker (apt)
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
    state: present
    update_cache: true

- name: Adding docker daemon.json
  become: true
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify: Restart docker service

- name: Force restart docker if needed
  ansible.builtin.meta: flush_handlers

- name: Creating new docker directory
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0750
  notify: Remove old docker directory

- name: Force create new docker directory
  ansible.builtin.meta: flush_handlers
