- name: Installing packages requirements (apt)
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - unzip
      - apt-transport-https
      - jq
      - python3-pip
    state: present
    update_cache: true

- name: Install python packages requirements (pip)
  ansible.builtin.pip:
    name:
      - docker-compose
      - docker
      - passlib
      - netaddr
  become: true
