---
# filebeat
- name: Copy filebeat.yml config file to the hosts
  become: true
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0644
  notify: Restart filebeat
  tags:
    - config

- name: Copy RedELK CA file to the hosts
  become: true
  ansible.builtin.copy:
    src: "{{ redelk_cert_path }}/ca/ca.crt"
    dest: /etc/filebeat/redelkCA.crt
    mode: 0644
  notify: Restart filebeat
  tags:
    - pki

- name: Recursively setting permissions of /etc/filebeat folder
  become: true
  ansible.builtin.file:
    path: /etc/filebeat
    state: directory
    recurse: true
    owner: root
    group: root
    mode: u=rwX,g=rX,o=-rwx
  tags:
    - config
