---
- name: restart autossh services
  become: true
  ansible.builtin.systemd:
    name: "autossh-tunnel-{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  with_items:
    - '{{ hostvars.values() | list | json_query("[?type==''redirector''].inventory_hostname") }}'
    - '{{ hostvars.values() | list | json_query("[?type==''c2''].inventory_hostname") }}'
  tags:
    - ssh
    - service

- name: restart docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: true
  tags:
    - docker
    - service
    - redelk-setup

- name: remove old docker directory
  become: true
  ansible.builtin.file:
    path: "/var/lib/docker"
    state: absent
  when: docker_dir != '/var/lib/docker'
  notify: symlink new docker directory
  tags:
    - docker
    - redelk-setup

- name: symlink new docker directory
  ansible.builtin.file:
    src: "{{ docker_dir }}"
    dest: /var/lib/docker
    owner: root
    group: root
    state: link
  when: docker_dir != '/var/lib/docker'
  tags:
    - docker
    - redelk-setup

- name: update-ca-certificates
  become: true
  ansible.builtin.command: "update-ca-certificates"
  tags:
    - pki
    - redelk-setup

- name: run init-letsencrypt.sh
  become: true
  ansible.builtin.command: "{{ optsec_dir }}/{{ redelk_user }}/init-letsencrypt.sh redelk-{{ redelk_install_type }}.yml {{ external_domain }}"
  args:
    chdir: "{{ optsec_dir }}/{{ redelk_user }}/"
  failed_when: false
  tags:
    - pki
    - redelk-setup
